config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  
 
  resources :profiles do
    member do
      get 'yearbook'
      get 'classmate'
    end
  end
  resources :schools
  resources :signatures,          only: [:create, :destroy]
  
  
  
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , registrations: "registrations"},skip: :registrations
  devise_scope :user do
  resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'registrations',
    as: :user_registration do
      get :cancel
    end
end
   

    

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  belongs_to :school
  has_many :signatures, dependent: :destroy
  has_many :signs, :class_name => 'Signature', :foreign_key => 'yearbook_id', dependent: :destroy
  

  validates :name, presence: true,  length: { maximum: 50 }
  validates :user_type, presence: true, :on => :update
  validates :school_id, presence: true, :on => :update
  validates :gender, presence: true, :on => :update
  validates :about_me,  length: { maximum: 1000 }
  validates :city,  length: { maximum: 100 }
  validate  :picture_size
  
  enum user_type: [:Student, :Teacher, :Principal, :Other]
  has_many :educations, :dependent => :destroy
  accepts_nested_attributes_for :educations,
                                  :allow_destroy => true,
                                  :reject_if     => proc { |attributes| attributes['institute'].blank? }
  has_many :occupations, :dependent => :destroy
  accepts_nested_attributes_for :occupations,
                                  :allow_destroy => true,
                                  :reject_if     => proc { |attributes| attributes['company'].blank? }
                                  
  
  mount_uploader :profile_pic, ProfilePicUploader
  
  # Validates the size of an uploaded picture.
    def picture_size
      if profile_pic.size > 3.megabytes
        errors.add(:profile_pic, "should be less than 3MB")
      end
    end

    def self.search(query)
          where("name like ?", "%#{query}%") 
    end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :yearbook, :classmate]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:new ,:destroy]
  before_action :prepare_schools
 
  # GET /profiles
  # GET /profiles.json
  def index
  
    if params[:search]
      @profiles = Profile.where(school_id: current_user.profile.school_id).search(params[:search]).order("name")
    else
      @profiles = Profile.where(school_id: current_user.profile.school_id).order('name')
    end
    
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    unless (@profile.school_id == current_user.profile.school_id)
      redirect_to current_user.profile
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    unless @profile.educations.blank?
      @profile.educations.each do |education|
        education ||= education_build
      end
    else
      @profile.educations.build
    end
    
    unless @profile.occupations.blank?
      @profile.occupations.each do |occupation|
        occupation ||= occupation_build
      end
    else
      @profile.occupations.build
    end
     
  end
  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def yearbook
    if (@profile.school_id == current_user.profile.school_id)
     @signature = current_user.profile.signatures.build
     session[:my_info]=@profile.id
     @signs=@profile.signs
    else
      redirect_to current_user.profile
    end
  end
  
  def classmate
    if (@profile.user_type == "Student")
     @classmates = Profile.where("school_id= ? AND batch= ? ",@profile.school_id, @profile.batch).order('name')
    else
      @classmates = Profile.where.not(user_type:'Student')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :name, :date_of_birth, :city, :about_me, :user_type, :school_id, :batch, :gender, :profile_pic,:remove_profile_pic,
                                      :educations_attributes =>[:id,:institute,:field,:from,:to, :_destroy],
                                      :occupations_attributes =>[:id,:company,:position,:city,:from,:to, :_destroy])
    end
    
    def prepare_schools
      @schools = School.all
    end
    
    def admin_user
       unless current_user.is_admin?
        redirect_to current_user.profile
       end
    end
    
    def correct_user
       unless (current_user.profile==@profile)
        redirect_to current_user.profile
       end
    end
    
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    def is_current_user(profile)
        current_user == profile.user
    end
    
    def has_signed(profile)
        @signer=current_user.profile
        @message=@signer.signatures.where(:yearbook_id => profile.id)
        if @message.exists?
            false
        else
            true
        end
    end
end

app/views/profiles/_classmate_partial.html.erb
<div class="classmates">
        <div style="margin-top:10px;margin-bottom: -40px;, margin-left:auto; margin-left:auto;display:block;" class="center-align">
         <i class="fa fa-commenting-o fa-5x"></i>
        </div>
    <ul class="collection">
          <li class="collection-item avatar">
            <%unless @classmates.empty?%>
            <% @classmates.each do |profile| %>
              <%unless @profile==profile%>
                <span class="title"><h6><%= link_to profile.name, profile %></h6></span>
                <%= image_tag display_pic(profile), :alt => "Profile Picture", :class => "circle responsive-img  "%>
                <div>
                  <%= profile.user_type%>
                <p><%= profile.user.email %>
                <%= profile.date_of_birth %>
                <%= profile.city %>
                </p>
                </div>
              <%end%>
            <%end%>
            <%if ((@classmates.count ==1) && (@profile.user_type == "Student"))%> <h4 class="teal-text center-align">Sorry! None of your classmates have joined Almanet yet.</h4> <%end%>
         <%end%>
         
            <% if  @profile.batch.blank?  %> 
             <%unless @profile.user_type == "Student"%>
               <h4 class="teal-text center-align">Sorry! None of your colleague has joined Almanet yet.</h4> 
             <%else%>
               <h4 class="teal-text center-align">Sorry! You have not specified your batch yet.</h4> 
             <%end%>
            <%end%>
         
    </ul>
</div> 
    

    
   

app/views/profiles/_education_fields.html.erb
<div class="nested-fields">
    <div class= "input-field">
    <%=f.label :institute, "Institution Name"%>
    <%=f.text_field :institute%>
    </div>
    <div class= "input-field">
    <%=f.label :field, "Specialization"%>
    <%=f.text_field :field%>
    </div>
    <div class= "field">
    <%=f.label :from%>
    <%= f.select :from, (1947..Time.now.year).to_a, :include_blank => "Select year" %>
    </div>
    <div class= "field">
    <%=f.label :to%>
    <%= f.select :to, (1947..Time.now.year).to_a, :include_blank => "Select year" %>
    </div>
     <%= link_to_remove_association "Remove ", f %>
</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile, html: {multipart: true}) do |f| %>
  <div class="card-panel hoverable" id="user_details">
       <!-- Errors-->
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <h5 class="teal-text">User Details</h5>
    <!-- Basic user info-->
    
    <!--Profile picture-->
    <div class="profile_pic_upload">
      <div class="upload-preview">
        <%= image_tag display_pic(@profile), :alt => "Profile Picture", :class => "responsive-img", :style=> "max-height:200px ; max-width: 200px;"%>
      </div>
      <%unless current_user.profile.profile_pic.blank?%>
      <div class="input-field">
          <%= f.check_box :remove_profile_pic %>
          <%= f.label :remove_profile_pic, "remove image" %>
      </div>
      <%end%>
      <div class="input-field">
        <%= f.file_field :profile_pic, :accept => 'image/jpeg,image/gif,image/png', :class => 'file'%>
        <br/>
      </div>
    </div>
    <br/>
    <div class="input-field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
      <br/>
      <%= f.select :batch, (1947..Time.now.year).to_a, :include_blank => "Select year" %>
    </div>
      <!--School id and user type -->
    <% if (@profile.school_id.blank? || @profile.user_type.blank?) %>
      <div class="field">
        <%= f.label "School*" %><br />
        <%= f.collection_select( :school_id, School.order(:school_name), :id, :school_name ,:include_blank => "Please select") %>
        <br/>
      </div>
      <div class="input-field">
        <%= f.label "You Are*" %><br />
        <%= f.select(:user_type, Profile.user_types.keys.map {|user_type| [user_type.titleize,user_type]}, :include_blank => "Please select") %>
        <br/>
      </div>
    <%end%>
      <!--end of school is and user type field-->
    <div class="input-field">
      <%= f.label :date_of_birth %><br />
      <%=f.date_field(:date_of_birth, :class => "datepicker", :include_blank => "Please select")%>
      <br/>
    </div>
     <%= f.label "Sex*" %>
    <div class="input-field">
      <%= f.radio_button :gender, "m"%>
      <%= f.label :gender_m, "Male" %><br/>
      <%= f.radio_button :gender, "f" %>
      <%= f.label :gender_f, "Female" %>
      <br/>
    </div>
    <br/>
    <a id="education_button"class="waves-effect waves-light btn" onclick="next_page('education');"><i class="material-icons right">navigate_next</i>Next</a>
  </div>
  
      <!-- education info-->
  <div class="card-panel hoverable"  id="education_details">
    <h5 class="teal-text">Education Details</h5>
      <div class= "input-fields">
       <%= f.fields_for :educations, @educations do |ff|%>
         <%= render 'education_fields', :f => ff %>
       <%end%>
      </div>
      <div class= "links">
       <%= link_to_add_association 'add education', f, :educations %>
      </div>
      <a id="occupation_button"class="waves-effect waves-light btn" onclick="next_page('occupation');"><i class="material-icons right">navigate_next</i>Next</a>
  </div>  
  
      <!-- Occupation info-->
  <div class="card-panel hoverable" id="occupation_details">
    <h5 class="teal-text">Occupation Details</h5>
      <div class= "input-fields">
       <%= f.fields_for :occupations, @occupations do |ff|%>
         <%= render 'occupation_fields', :f => ff %>
       <%end%>
      </div>
      <div class= "links">
       <%= link_to_add_association 'Add occupation', f, :occupations %>
      </div>
       <a id="other_button"class="waves-effect waves-light btn" onclick="next_page('other');"><i class="material-icons right">navigate_next</i>Next</a>
  </div>
        
  <div class="card-panel hoverable" id="other_info"> 
    <h5 class="teal-text">Other Details</h5>
    <div class="field">
      <%= f.label "Current city" %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :about_me %><br>
      <%= f.text_area :about_me %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>





<script type="text/javascript" >

  function next_page(id) {
    console.log('sdfsd');
    document.getElementById(id).click();
  }
  
  $(document).ready(function(){
    var preview = $(".upload-preview img");
    
    $(".file").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
    
    
    $('#profile_profile_pic').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 3) {
      alert('Maximum file size is 3MB. Please choose a smaller file.');
    }
  });

});
</script>

app/views/profiles/_occupation_fields.html.erb
<div class="nested-fields">
    <div class= "input-field">
    <%=f.label :company, "Company"%>
    <%=f.text_field :company%>
    </div>
    <div class= "input-field">
    <%=f.label :position, "Position"%>
    <%=f.text_field :position%>
    </div>
    <div class= "field">
    <%=f.label :from%>
    <%= f.select :from, (1947..Time.now.year).to_a, :include_blank => "Select year" %>
    </div>
    <div class= "field">
    <%=f.label :to%>
    <%= f.select :to, (1947..Time.now.year).to_a, :include_blank => "Select year" %>
    </div>
    <div class= "input-field">
    <%=f.label :city, "City"%>
    <%=f.text_field :city%>
    </div>
        <%= link_to_remove_association "Remove ", f %>
    
     
    
</div>

app/views/profiles/_profile_card.html.erb
<div class="card-panel hoverable" style="border-top: 1px solid  #009688; border-bottom: 1px solid  #009688; min-height:250px;">
  
  <%unless user_profile== @profile%>
    <div class="right">
      <%if (@profile.user_type == "Student")%>
        <%= link_to 'Sign Yearbook', yearbook_profile_path(@profile)%><br/>
      <%else%>
        <%= link_to 'Say Thanks!', yearbook_profile_path(@profile)%><br/>
      <%end%>
        <%= link_to 'Request to Contact', edit_profile_path(@profile)%>
    </div>
  <%end%>
  
  <div class="row">
    <div class="col s3" style="padding-right: 0px; padding-left: 0px;">
      <div class="img_container" style="overflow: hidden; padding-right: 0px;">
         <%= image_tag display_pic(@profile), :alt => "Profile Picture", :class => "responsive-img", :id => "profile_pic_other"%>
      </div>
    </div>
      <div class="col s5" style="padding-right: 0px;">
        <h5 class><%= @profile.name %></h5>
        <%=@profile.user_type%> at <%= @profile.school.school_name%>
        <%= @profile.batch%>
         <p>
          <%= @profile.city %>
         </p>
      </div>
    </div>
</div>

app/views/profiles/_show_partial.html.erb
<!-- Basic Info section -->
<div class="user">
    <div class="card-panel hoverable" style="border-top: 1px solid #009688;">
        <h5 class="center-align teal-text">User</h5>
        <p>
        <strong>About me:</strong>
        <%= @profile.about_me %>
        </p>
        <p>
        <strong>Date of birth:</strong>
        <%= @profile.date_of_birth %>
        </p>
        <p>
        <strong>School:</strong>
        <%unless @profile.school_id.nil?%>
        <%= @profile.school.school_name %>
        <%end%>
        </p>
    </div>
</div>

<!-- Education section -->
<div class="education">
    <div style="margin-top:10px;margin-bottom: -40px;, margin-left:auto; margin-left:auto;display:block;" class="center-align">
      <i class="fa fa-graduation-cap fa-5x"></i>
    </div>
    <div class="card-panel hoverable" style="border-top: 1px solid #009688;">
      <h5 class="center-align teal-text">Education</h5>
        <strong>School:</strong>
        <%@profile.educations.each do |education|%>
          <h5><%=education.institute%></h5>
          <ul>
            <li><%=education.field%></li>
            <li><%=education.from%></li>
            <li><%=education.to%></li>
          </ul>
        <%end%>
        <%unless @profile.school_id.nil?%>
          <h5><%= @profile.school.school_name %></h5>
        <%end%>
    </div>
</div>

<!-- Occupation section -->
<div class="occupation">
    <div style="margin-top:10px;margin-bottom: -40px;, margin-left:auto; margin-left:auto;display:block;" class="center-align">
      <i class="fa fa-briefcase fa-5x"></i>
    </div>
    <div class="card-panel hoverable" style="border-top: 1px solid #009688;">
      <h5 class="center-align teal-text">Occupation</h5>
        <strong>Occupation:</strong>
        <%@profile.occupations.each do |occupation|%>
          <h5><%=occupation.company%></h5>
          <ul>
            <li><%=occupation.position%></li>
            <li><%=occupation.from%></li>
            <li><%=occupation.to%></li>
          </ul>
        <%end%>
    </div>
</div>

app/views/profiles/_tabs_nav.html.erb
<%if current_user.profile == @profile %>
  <nav class="white">
    <ul>
      <li class="tab col s3"><%= link_to 'Profile', profile_path(@profile),class: "teal-text center-align"%></li>
      <li class="tab col s3"><%= link_to 'Yearbook', yearbook_profile_path(@profile),class: "teal-text center-align"%></li>
      <%if (@profile.user_type == "Student")%>
        <li class="tab col s3"><%= link_to 'Classmates', classmate_profile_path(@profile),class: "teal-text center-align"%></li>
      <%else%>
       <li class="tab col s3"><%= link_to 'Colleagues', classmate_profile_path(@profile),class: "teal-text center-align"%></li>
      <%end%>
      <li class="tab col s3"><a class="teal-text center-align" href="#test4">Messages</a></li>
    </ul>
  </nav>
<%else%>
  <nav class="white">
    <ul>
      <li class="tab col s4"><%= link_to 'Profile', profile_path(@profile),class: "teal-text center-align"%></li>
      <li class="tab col s4"><%= link_to 'Yearbook', yearbook_profile_path(@profile),class: "teal-text center-align"%></li>
      <%if (@profile.user_type == "Student")%>
        <li class="tab col s4"><%= link_to 'Classmates', classmate_profile_path(@profile),class: "teal-text center-align"%></li>
      <%else%>
       <li class="tab col s4"><%= link_to 'Colleagues', classmate_profile_path(@profile),class: "teal-text center-align"%></li>
      <%end%>
      
    </ul>
  </nav>
<%end%>

app/views/profiles/_yearbook_partial.html.erb
<%unless is_current_user(@profile)%>
    <%if has_signed(@profile)%>
    <div class="card-panel hoverable">
        <%= form_for(@signature) do |f| %>
          <div class="input-field">
            <%if (@profile.user_type == "Student")%>
                <%= f.text_area :content, placeholder:  "Sign #{@profile.name}'s yearbook..."%>
            <%else%>
                 <%= f.text_area :content, placeholder:  "Say a warm thanks to #{@profile.name}..."%>
            <%end%>
          </div>
          <div class="input-field">
            <%= f.file_field :image, :accept => 'image/jpeg,image/gif,image/png', :class => 'file'%>
          <br/>
          </div>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
    </div>
    <%end%>
<%end%>

<div class="posts">
        <div style="margin-top:10px;margin-bottom: -40px;, margin-left:auto; margin-left:auto;display:block;" class="center-align">
         <i class="fa fa-commenting-o fa-5x"></i>
        </div>
      <%unless @signs.empty?%>
        <% @signs.each do |sign| %>
        <div class="card-panel hoverable" >
             <p class="teal-text right-align" style="font-size:0.8em;">Posted <%= time_ago_in_words(sign.created_at) %> ago.</p>
        <div  style="position:relative;">
            <div class="post_info" style="position:absolute;right:10px;top:10px;">
                
                <% if  is_current_user(@profile) %>
                <a class='dropdown-button' href='#' data-activates='dropdown_post' data-alignment="top"><i class="fa fa-cog"></i></a>
                <ul id='dropdown_post' class='dropdown-content'>
                    <li><a href="#!">one</a></li>
                    <li><a href="#!">Only me</a></li>
                    <li><%= link_to "Delete", sign, method: :delete,
                                                   data: { confirm: "You sure?" } %></li>
                 </ul>
                <% end %>
            </div>
            <div class="signer_info">
                <%= link_to profile_path(sign.profile) do%>
                <%= image_tag display_pic(sign.profile), :alt => "user picture", :class => "circle responsive-img  " , :style=> " float:left;max-height:60px; max-width:60px;margin-right:10px;"%>
                <h6 style="font-size:1.3em;"><%=sign.profile.name%></h6>signed yearbook!
                <%end%><br/>
            </div>
            <div class="signer_content">
                <p><%=sign.content%></p>
                <%unless sign.image.blank?%>
                <%= image_tag sign.image.url, :alt => "Picture", :class => "responsive-img"%>
                <%end%><br/>
            </div>
            
        </div>
        </div>
        <%end%>
      <%else%>
          <div class="card-panel hoverable" style="min-height:300px;">
               <h5 class="center-align teal-text">Nobody has signed this yearbook yet!</h5>
          </div>
      <%end%>
</div> 
    

    
   

app/views/profiles/classmate.html.erb
<div class= "row" >
   <!-- sidebar section -->
  <%unless is_current_user(@profile)%>
    <%= render 'layouts/sidebar'%>
  <%end%>
  
  
   <!-- Profile section -->
<%if is_current_user(@profile)%>
  <div class= "col s12 m12 l10">
<%else%>
  <div class= "col s9">
  <%end%>
  
    <div class ="container">
  
     <!-- Profile card section -->
      <%= render 'profile_card'%>
      
      <!--tabs navigation bar-->
      <%= render 'tabs_nav'%>
      
      <!--Yearbook partial (rendering posts)-->
      <%= render 'classmate_partial'%>

    </div>
  </div>
    
    
      <div class= "col s1"> 
    
      </div>
</div>

app/views/profiles/edit.html.erb
<div class="row"> 
  <div class="col s6 offset-s2">
    <h2 class="center-align">Editing Profile</h2>
  </div>
</div>
<div class="row"> 
  <div class="col s6 offset-s2 card-panel hoverable">
    <ul class="tabs">
        <li class="tab col s3"><a href="#user_details" >User </a></li>
        <li class="tab col s3"><a href="#education_details" id="education" >Education</a></li>
        <li class="tab col s3"><a href="#occupation_details" id="occupation">Occupation</a></li>
        <li class="tab col s3"><a href="#other_info" id="other">Other</a></li>
      </ul>
  </div>
</div>

<div class="row"> 
  <div class="col s6 offset-s2">
    <%= render 'form' %>
  </div>
  <div class="col s2">
    <div class="toc-wrapper">
      <div style="height: 1px;">
        <ul class="section table-of-contents">
          <li><a href="#user_details">User Information</a></li>
          <li><a href="#education_details">Education Details</a></li>
          <li><a href="#occupation_details">Occupation Details</a></li>
          <li><a href="#other_info">Other Information</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row" style="margin-bottom: 0px;">
  <div class="col s4 offset-s4 ">
    <h3 class=" teal-text center-align">School buddies</h3>
    <nav class="grey lighten-3">
        <div class="nav-wrapper">
            <%= form_tag(profiles_path, :method => "get", id: "search-form") do %>
                <div class="input-field">
                    <%= search_field_tag :search, params[:search], placeholder: "Search " %>
                    <%= submit_tag "Search", :name => nil %><br/>
                    <label for="search"><i class="material-icons" style="color:teal; padding-left: 10px;">search</i></label>
                    <i class="material-icons">close</i>    
                </div>
            <% end %>               
        </div>
    </nav>
    <br/>
</div>
</div>


<div class="row">
  <div class="col s8 offset-s2 ">
    
    <ul class="collection">
          <li class="collection-item avatar">
            <%unless @profiles.empty?%>
            <% @profiles.each do |profile| %>
              <%unless user_profile==profile%>
                <span class="title"><h6><%= link_to profile.name, profile %></h6></span>
                <%= image_tag display_pic(profile), :alt => "Profile Picture", :class => "circle responsive-img  "%>
                <div>
                  <%= profile.user_type%>
                <p><%= profile.user.email %>
                <%= profile.date_of_birth %>
                <%= profile.city %>
                </p>
                </div>
              <%else%>
                <%if @profiles.count == 1%><h4 class="teal-text center-align">Sorry! No other users from your school yet</h4><%end%>
              <%end%>
                <%if current_user.is_admin?%>
                <%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>
              <% end %>
              <br/>
            <%else%>
                <h4 class="teal-text center-align">No results found</h4>
               
            <%end%>
          </li>
    </ul>
    
    <%if current_user.is_admin?%>
    <%= link_to 'Add Profile', new_profile_path,{:class => "waves-effect waves-light btn"} %>
    <%end%>
 </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class= "row" >
   <!-- sidebar section -->
  <%unless is_current_user(@profile)%>
    <%= render 'layouts/sidebar'%>
  <%end%>
  
  
   <!-- Profile section -->
<%if is_current_user(@profile)%>
  <div class= "col s12 m12 l10">
<%else%>
  <div class= "col s9">
  <%end%>
  
    <div class ="container">
  
     <!-- Profile card section -->
      <%= render 'profile_card'%>
      
      <!--tabs navigation bar-->
      <%= render 'tabs_nav'%>
      
      <!--Profile attributes like education occupation etc-->
      <%= render 'show_partial'%>
    </div>
  </div>
    
    
      <div class= "col s1"> 
    
      </div>
</div>

app/views/profiles/yearbook.html.erb
<div class= "row" >
   <!-- sidebar section -->
  <%unless is_current_user(@profile)%>
    <%= render 'layouts/sidebar'%>
  <%end%>
  
  
   <!-- Profile section -->
<%if is_current_user(@profile)%>
  <div class= "col s12 m12 l10">
<%else%>
  <div class= "col s9">
  <%end%>
  
    <div class ="container">
  
     <!-- Profile card section -->
      <%= render 'profile_card'%>
      
      <!--tabs navigation bar-->
      <%= render 'tabs_nav'%>
      
      <!--Yearbook partial (rendering posts)-->
      <%= render 'yearbook_partial'%>

    </div>
  </div>
    
    
      <div class= "col s1"> 
    
      </div>
</div>

<script type="text/javascript">
  $('#tagged_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 3) {
      alert('Maximum file size is 3MB. Please choose a smaller file.');
    }
  });
</script>