config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  
 
  resources :profiles do
    member do
      get 'yearbook'
      get 'classmate'
    end
  end
  resources :schools
  resources :signatures,          only: [:create, :destroy]
  
  
  
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , registrations: "registrations"},skip: :registrations
  devise_scope :user do
  resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'registrations',
    as: :user_registration do
      get :cancel
    end
end
   

    

end

app/models/school.rb
class School < ActiveRecord::Base
    has_many :profiles
    
    def self.search(query)
        where("school_name like ?", "%#{query}%") 
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:edit,:update,:destroy]
  before_action :admin_user, only:[:edit,:update,:destroy]
  
  # GET /schools
  # GET /schools.json
  def index
   
    if params[:search]
      @schools = School.search(params[:search]).order("school_name")
    else
      @schools= School.all.order('school_name')
    end
    
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:school_name, :address, :phone_number, :email, :search)
    end
    
    def admin_user
      unless current_user.is_admin?
       redirect_to schools_url
      end
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
      <%= form_for(@school) do |f| %>
      <% if @school.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>
  
        <ul>
        <% @school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= f.label :school_name %><br>
        <%= f.text_field :school_name %>
      </div>
      <div class="field">
        <%= f.label :address %><br>
        <%= f.text_area :address %>
      </div>
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="actions">
        <%= f.submit(:class => "waves-effect waves-light btn " )%>
      </div>
    <% end %>

app/views/schools/edit.html.erb
<div class="row"> 
  <div class="col s6 offset-s3" >
    <div class="card-panel hoverable">
        <h3 class= "center-align">Editing School</h3>

        <%= render 'form' %>
        
        <%= link_to 'Show', @school %> |
        <%= link_to 'Back', schools_path %>
        <%= button_to "Delete", school_path(@school), data: { confirm: "Are you sure?" }, method: :delete %>
    </div>
  </div>
</div>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s4 offset-s4 ">
       <h1 class="teal-text center-align">Schools</h1>
    
    <nav class="grey lighten-3">
        <div class="nav-wrapper">
            <%= form_tag(schools_path, :method => "get", id: "search-form") do %>
                <div class="input-field">
                    <%= search_field_tag :search, params[:search], placeholder: "Search " %>
                    <%= submit_tag "Search", :name => nil %><br/>
                    <label for="search"><i class="material-icons" style="color:teal; padding-left: 10px;">search</i></label>
                    <i class="material-icons" onclick="">close</i>    
                </div>
            <% end %>               
        </div>
    </nav>
  </div>
</div>
<div class="row">
  <div class="col s8 offset-s2 ">
    <ul class="collection">
          <li class="collection-item">
            <%unless @schools.empty?%>
            <% @schools.each do |school| %>
            <span class="title"><h5><%= school.school_name.to_s.capitalize %></h5></span>
            <p><%= school.address %><br/>
               <%= school.email %><br/>
               <%= school.phone_number %><br/>
               <%= link_to 'View', school , {:class => "secondary-content waves-effect waves-light btn"}%>
              <%if ((user_signed_in? ) && (current_user.is_admin?))%>
               <%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %>
               <%= link_to 'Edit', edit_school_path(school) %>
              <%end%>
              <br/>
              <br/>
            </p>
            <% end %>
            <%else%>
                <h4 class="teal-text center-align">No results found</h4>
                <h6 class="center-align">Please add your School</h6>
            <%end%>
          </li>
    </ul>
    <div class="center">
        <%= link_to 'Add your School', new_school_path,{:class => "waves-effect waves-light btn"} %>
    </div>
 </div>
</div>

app/views/schools/new.html.erb
<div class="row"> 
  <div class="col s6 offset-s3" >
    <div class="card-panel hoverable">
        <h3 class= "center-align">New School</h3>
        <%= render 'form' %>
        <br/>
  </div>
  </div>
</div>

app/views/schools/show.html.erb
<div class="row"> 
  <div class="col s6 offset-s3" >
    <div class="card-panel hoverable">
        <h3 class= "center-align"><%= @school.school_name %></h3>
        <p>
          <strong>Address:</strong>
          <%= @school.address %>
        </p>
        
        <p>
          <strong>Phone number:</strong>
          <%= @school.phone_number %>
        </p>
        
        <p>
          <strong>Email:</strong>
          <%= @school.email %>
        </p>

        <%= link_to 'Edit', edit_school_path(@school) %> |
        <%= link_to 'Back', schools_path %>
    </div>
  </div>
</div>