config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  
 
  resources :profiles do
    member do
      get 'yearbook'
      get 'classmate'
    end
  end
  resources :schools
  resources :signatures,          only: [:create, :destroy]
  
  
  
  devise_for :users , :controllers => { :omniauth_callbacks => "omniauth_callbacks" , registrations: "registrations"},skip: :registrations
  devise_scope :user do
  resource :registration,
    only: [:new, :create, :edit, :update],
    path: 'users',
    path_names: { new: 'sign_up' },
    controller: 'registrations',
    as: :user_registration do
      get :cancel
    end
end
   

    

end

app/views/layouts/_error.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
<%end%>
    
<%if alert%>
    <p class="alert"><%= alert %></p>
<%end%>
    

app/views/layouts/_footer.html.erb
<footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">About AlmaNet</h5>
          <p class="grey-text text-lighten-4"> We aim to connect yo to your forgotten school buddies, mentors, seniors.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="https://jp.linkedin.com/in/kumar91gopi"><i class="fa fa-linkedin-square"></i> LinkedIn</a></li>
            <li><a class="white-text" href="https://twitter.com/Gopi_k_mishra"><i class="fa fa-twitter-square"></i> Twitter</a></li>
            <li><a class="white-text" href="https://www.facebook.com/kumar91gopi"><i class="fa fa-facebook-square"></i> Facebook</a></li>
            <li><a class="white-text" href="https://github.com/kumar91gopi"><i class="fa fa-github-square"></i> GitHub</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        <i class="fa fa-copyright"></i> RPVV YearBook All Rights Reserved</a>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<div  class="navbar-fixed">
  <nav  role="navigation" class="teal">
    <div class="nav-wrapper container">
        <%unless user_signed_in? %>
            <%=link_to "AlmaNet",  root_path , class:"brand-logo",id:"logo-container"%>
        <%else%>
            <%unless user_profile.school.blank?%> 
            <%=link_to "AlmaNet",  profile_path( user_profile) , class:"brand-logo",id:"logo-container"%>
            <%else%>
            <%=link_to "Almanet",  "#" , class:"brand-logo",id:"logo-container"%>
            <%end%>
        <%end%>
      <ul class="right hide-on-med-and-down">
         <% unless user_signed_in? %>
         <li><%=link_to "Home",  root_path %></li>
         <li><%=link_to "Schools",  schools_path %></li>
         <li><%=link_to "About us",  about_path %></li>
         <li><%=link_to "Sign In",  new_user_session_path %></li>
         <%else%>
            <%unless user_profile.school.blank?%>           
            <li><%= link_to("My Profile", profile_path( user_profile)) %></li>
            <li><%=link_to "School buddies",  profiles_path %></li>
            <%else%>
             <li><%= link_to("My Profile", edit_profile_path( user_profile)) %></li>
            <%end%>
             <!-- Dropdown Trigger -->
            <li><a class="dropdown-button" href="#!" data-beloworigin="true" data-activates="dropdown1">
                <%= user_profile.name%>
                <i class="material-icons right">arrow_drop_down</i>
              </a>
          </li>

              <!-- Dropdown Structure -->
              <ul id='dropdown1' class='dropdown-content'>
                <li><%= link_to('Edit Profile',  edit_profile_path( user_profile)) %></li>
                <li class="divider"></li>
                <li><%= link_to('User settings',  edit_user_registration_path) %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              </ul>
         <%end%>
      </ul>
      <ul>
    <%if user_signed_in?%>
      <li class="right">
      <span class="hide-on-large-only"><%= link_to destroy_user_session_path, :method => :delete do %><i class="fa fa-sign-out"></i><%end%></span>
      </li>
    <%else%>
      <li class="right">
      <span class="hide-on-large-only"><%= link_to new_user_session_path do %><i class="fa fa-sign-in"></i><%end%></span>
      </li>
    <%end%>
      </ul>
      <%= render 'layouts/mobile_sidebar'%>
    </div>
  </nav>
</div>

app/views/layouts/_mobile_sidebar.html.erb
<ul id="nav-mobile" class="side-nav">
         <%unless user_signed_in?%>
             <li><%=link_to "Home",  root_path %></li>
             <li><%=link_to "Schools",  schools_path %></li>
             <li><%=link_to "About us",  about_path %></li>
         <%else%>
              <li class="logo">
                  <%= link_to(image_tag display_pic(user_profile), :alt => "Profile Picture", \
                                      :class => "profile_pic circle responsive-img") %><br/>
                  <%= link_to(user_profile.name, profile_path( user_profile), class: "center-align") %>
              </li>
              <li class="no-padding">
              <ul class="collapsible collapsible-accordion">
                <li>
                  <a class="collapsible-header">Settings<i class="material-icons right">arrow_drop_down</i></a>
                  <div class="collapsible-body">
                    <ul>
                        <li><%= link_to('Edit Profile', edit_profile_path( user_profile)) %></li>
                        <li class="divider"></li>
                        <li><%= link_to('Password settings',  edit_user_registration_path) %></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li><%=link_to "School buddies",  profiles_path %></li>
         <%end%>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>

app/views/layouts/_shim.html.erb
 <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
<div class= "col s2  " style="height: 100vh;" id="sidebar">
    <ul class="collection with-header" id="abc" >
        <li class="collection-header">
          <%= link_to profile_path(user_profile) do%>
          <%= image_tag display_pic(user_profile), :alt => "Profile Picture", :class => "profile_pic circle responsive-img"%>
          <h5 class=" teal-text center-align"><%= user_profile.name %></h5>
          <%end%>
        </li>
        <%= link_to 'My Yearbook', yearbook_profile_path(user_profile), class: "collection-item"%>
        <a href="#!" class="collection-item">Contact requests</a>
        <%= link_to "Edit Profile",edit_profile_path(user_profile), class: "collection-item"%>
        <br/>
    </ul> 
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>AlmaNet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
 
  <%= csrf_meta_tags %>
  <!-- Google font -->
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Ubuntu" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <header>
        
        <%= render 'layouts/header' %>
        <%= render 'layouts/error'%>
    </header>
    
    <main>
        <%= yield %>
    </main>
    
    
    
     <%= render 'layouts/footer' %>
  
   
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= debug(params) if Rails.env.development? %>
    
</body>
</html>